spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
    serialization:
      # Date返回前端转时间戳 但不能解决LocalDateTime转时间戳（JacksonCustomizerConfig类解决）
      write-dates-as-timestamps: true
    #设置空如何序列化
    default-property-inclusion: non_empty
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  application:
    name: consumer-client
  cloud:
    config:
      enabled: false
server:
  port: 8090
mybatis:
  mapper-locations: classpath*:mapper/*xml
  type-aliases-package: com.zime.consumerclient
  configuration:
    map-underscore-to-camel-case: true      #开启驼峰命名
log4j:
  logger:
    Java:
      sql:
        Connection: DEBUG
    com:
      ibatis: DEBUG
      ibatis.common.jdbc.ScriptRunner: DEBUG
      ibatis.common.jdbc.SimpleDataSource: DEBUG
    java:
      sql:
        PreparedStatement: DEBUG　
        Statement: DEBUG
gaode:
  key: a4c982fd12f2b598150e93cc9d8f4143
